defmodule NumbersEvolution.Strategies.OpenRouterService do
  @moduledoc """
  OpenRouter service for AI-powered lottery strategy generation.

  This service implements the NumbersEvolution.AIProvider behaviour and provides
  high-level strategy generation using OpenRouter AI. It handles business logic
  including rate limiting, input validation, response processing, and error handling.

  Uses NumbersEvolution.Client.OpenRouterClient for low-level HTTP communication.
  """

  require Logger

  @behaviour NumbersEvolution.AIProvider

  alias NumbersEvolution.Client.OpenRouterClient

  # Rate limiting constants
  @max_generations_per_day 5
  @rate_limit_window_ms 86_400_000  # 24 hours

  # API constants
  @default_system_message """
  You are an expert Eurojackpot strategy generator. Based on user input, create an innovative lottery strategy.

  You MUST respond with ONLY valid JSON matching this exact schema:
  {
    "name": "Strategy Name (max 100 chars)",
    "type": "ai_generated",
    "rules": {
      "weights": {
        "hot": 0.0-1.0,
        "cold": 0.0-1.0,
        "random": 0.0-1.0
      }
    }
  }

  The weights must sum to exactly 1.0. Do not include any other text or explanation.
  """

  @response_schema %{
    "type" => "object",
    "properties" => %{
      "name" => %{"type" => "string", "maxLength" => 100},
      "type" => %{"type" => "string", "enum" => ["ai_generated"]},
      "rules" => %{
        "type" => "object",
        "properties" => %{
          "weights" => %{
            "type" => "object",
            "properties" => %{
              "hot" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
              "cold" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
              "random" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0}
            },
            "required" => ["hot", "cold", "random"]
          }
        },
        "required" => ["weights"]
      }
    },
    "required" => ["name", "type", "rules"]
  }

  @doc """
  Generates a strategy based on a text prompt using OpenRouter AI.

  ## Parameters
  - `prompt`: String user prompt (10-500 characters)

  ## Returns
  - `{:ok, strategy_response}` - Successfully generated strategy
  - `{:error, :rate_limit_exceeded}` - User exceeded daily limit
  - `{:error, :prompt_too_short | :prompt_too_long | :invalid_content}` - Invalid prompt
  - `{:error, :api_error}` - AI service unavailable
  - `{:error, :invalid_response}` - AI returned invalid response
  """
  @impl true
  @spec generate_strategy(String.t()) ::
          {:ok, NumbersEvolution.AIProvider.strategy_response()} | {:error, atom()}
  def generate_strategy(prompt) do
    with :ok <- validate_prompt(prompt),
         :ok <- OpenRouterClient.validate_config(),
         {:ok, request_payload} <- build_request_payload(prompt),
         {:ok, response} <- OpenRouterClient.chat_completion(request_payload),
         {:ok, strategy_attrs} <- parse_response(response) do
      {:ok,
       %{
         strategy_name: strategy_attrs["name"],
         description: "AI-generated strategy based on: #{String.slice(prompt, 0, 100)}",
         reasoning: "Generated by AI based on user prompt",
         rules: strategy_attrs["rules"]
       }}
    else
      {:error, reason} ->
        Logger.warning("OpenRouter strategy generation failed: #{inspect(reason)}")
        {:error, reason}
    end
  rescue
    exception ->
      Logger.error("OpenRouter unexpected error: #{inspect(exception)}")
      {:error, :generation_failed}
  end

  @doc """
  Validates a user prompt for strategy generation.

  ## Parameters
  - `prompt`: String to validate

  ## Returns
  - `:ok` - Prompt is valid
  - `{:error, :prompt_too_short}` - Prompt shorter than 10 characters
  - `{:error, :prompt_too_long}` - Prompt longer than 500 characters
  - `{:error, :invalid_content}` - Prompt contains forbidden content
  """
  @spec validate_prompt(String.t()) :: :ok | {:error, atom()}
  def validate_prompt(prompt) when is_binary(prompt) do
    cond do
      String.length(prompt) < 10 ->
        {:error, :prompt_too_short}

      String.length(prompt) > 500 ->
        {:error, :prompt_too_long}

      contains_forbidden_content?(prompt) ->
        {:error, :invalid_content}

      true ->
        :ok
    end
  end

  def validate_prompt(_), do: {:error, :invalid_prompt}

  @doc """
  Checks if user has exceeded rate limit for AI generation.

  ## Parameters
  - `user_id`: User identifier

  ## Returns
  - `:ok` - User can generate
  - `{:error, :rate_limit_exceeded}` - User exceeded limit
  """
  @spec check_rate_limit(binary()) :: :ok | {:error, :rate_limit_exceeded}
  def check_rate_limit(user_id) do
    table = get_rate_limit_table()
    now = System.system_time(:millisecond)

    case :ets.lookup(table, user_id) do
      [{^user_id, count, window_start}] when now - window_start < @rate_limit_window_ms ->
        if count >= @max_generations_per_day do
          {:error, :rate_limit_exceeded}
        else
          :ok
        end

      _ ->
        # New window or no record
        :ok
    end
  end

  @doc """
  Increments the rate limit counter for a user.
  Should be called after successful generation.
  """
  @spec increment_rate_limit(binary()) :: :ok
  def increment_rate_limit(user_id) do
    table = get_rate_limit_table()
    now = System.system_time(:millisecond)

    case :ets.lookup(table, user_id) do
      [{^user_id, count, window_start}] when now - window_start < @rate_limit_window_ms ->
        :ets.insert(table, {user_id, count + 1, window_start})

      _ ->
        # New window
        :ets.insert(table, {user_id, 1, now})
    end

    :ok
  end

  # Private methods

  defp build_request_payload(prompt, opts \\ []) do
    config = Application.get_env(:numbers_evolution, :openrouter, %{})
    model = Keyword.get(opts, :model, config[:default_model] || "openai/gpt-4o-mini")

    payload = %{
      model: model,
      messages: [
        %{role: "system", content: @default_system_message},
        %{role: "user", content: sanitize_prompt(prompt)}
      ],
      response_format: %{
        type: "json_schema",
        json_schema: %{
          name: "lotto_strategy",
          strict: true,
          schema: @response_schema
        }
      },
      temperature: 0.7,
      max_tokens: 1000
    }

    {:ok, payload}
  end

  defp parse_response(%{"choices" => [%{"message" => %{"content" => content}} | _]}) do
    with {:ok, parsed} <- Jason.decode(content),
         :ok <- validate_response_schema(parsed) do
      {:ok, parsed}
    else
      {:error, %Jason.DecodeError{}} ->
        {:error, :invalid_json_response}

      {:error, :invalid_schema} ->
        {:error, :invalid_response_schema}
    end
  end

  defp parse_response(_), do: {:error, :invalid_response_format}

  defp validate_response_schema(data) do
    # Basic validation - in production, consider using ExJsonSchema
    required_keys = ["name", "type", "rules"]
    has_required = Enum.all?(required_keys, &Map.has_key?(data, &1))

    if has_required do
      # Validate weights sum to 1.0
      with %{"rules" => %{"weights" => weights}} <- data,
           true <- is_map(weights),
           true <-
             Map.has_key?(weights, "hot") and Map.has_key?(weights, "cold") and
               Map.has_key?(weights, "random"),
           sum when sum >= 0.99 and sum <= 1.01 <-
             weights["hot"] + weights["cold"] + weights["random"] do
        :ok
      else
        _ -> {:error, :invalid_schema}
      end
    else
      {:error, :invalid_schema}
    end
  end

  defp sanitize_prompt(prompt) do
    prompt
    |> String.trim()
    |> String.slice(0, 500)
    |> remove_forbidden_patterns()
  end

  defp contains_forbidden_content?(prompt) do
    forbidden_patterns = [
      ~r/(?i)ignore.*previous/i,
      ~r/(?i)system.*prompt/i,
      ~r/(?i)reveal.*prompt/i,
      ~r/(?i)internal.*instruction/i
    ]

    Enum.any?(forbidden_patterns, &Regex.match?(&1, prompt))
  end

  defp remove_forbidden_patterns(prompt) do
    forbidden_patterns = [
      ~r/(?i)ignore.*previous/i,
      ~r/(?i)system.*prompt/i,
      ~r/(?i)reveal.*prompt/i,
      ~r/(?i)internal.*instruction/i
    ]

    Enum.reduce(forbidden_patterns, prompt, fn pattern, acc ->
      Regex.replace(pattern, acc, "")
    end)
  end

  defp get_rate_limit_table do
    case :ets.whereis(:openrouter_rate_limits) do
      :undefined ->
        :ets.new(:openrouter_rate_limits, [:set, :public, :named_table])
        :openrouter_rate_limits

      table ->
        table
    end
  end
end
