import Config

# Load environment variables from .env file
env_file_path = Path.expand(".env", File.cwd!())

if File.exists?(env_file_path) do
  env_file_path
  |> File.read!()
  |> String.split("\n", trim: true)
  |> Enum.each(fn line ->
    case String.split(line, "=", parts: 2) do
      [key, value] ->
        System.put_env(key, value)

      _ ->
        :ok
    end
  end)
end

# Configure your database
config :numbers_evolution, NumbersEvolution.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "numbers_evolution_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :numbers_evolution, NumbersEvolutionWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "7R4NcRYWpJgC/5A+eiaGE8Y6O6EYttFa+NvW6p+d8djUuSxwcABktlO1AeCHemH6",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:numbers_evolution, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:numbers_evolution, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :numbers_evolution, NumbersEvolutionWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/numbers_evolution_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :numbers_evolution, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Configure admin user email
config :numbers_evolution, :admin_user, System.get_env("ADMIN_USER") || "aa@aa.aa"

# Configure OpenRouter AI provider for development
config :numbers_evolution, :ai_provider, NumbersEvolution.Strategies.OpenRouterService

config :numbers_evolution, :openrouter,
  api_key: System.get_env("OPENROUTER_API_KEY"),
  base_url: "https://openrouter.ai/api/v1",
  default_model: "openai/gpt-4o-mini",
  timeout: 30_000,
  rate_limit_per_hour: 100

# Automatically import draws (Lotto archive backfill + latest Eurojackpot)
# shortly after boot and periodically
config :numbers_evolution, auto_import_draws: true
